language: C++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ 'ninja-build', 'cmake', 'g++-5' ]
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ 'ninja-build', 'cmake', 'g++-5' ]
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          packages: [ 'ninja-build', 'cmake', libc++-dev ]
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    - os: linux
      addons:
        apt:
          packages: [ 'ninja-build', 'cmake', libc++-dev ]
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd DIVA
  - cmake . -Bbuild -G Ninja
  - cmake --build build
  - ./build/bin/unittests
