language: C++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ 'ninja-build', 'cmake', 'g++-5' ]
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ 'ninja-build', 'cmake', 'g++-5' ]
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      compiler: clang
      addons:
        apt:
          packages: [ 'ninja-build', 'cmake', libc++-dev ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      compiler: clang
      addons:
        apt:
          packages: [ 'ninja-build', 'cmake', libc++-dev ]
      env: CMAKE_BUILD_TYPE=RELEASE


install: cmake
script:
  - cd DIVA
  - cmake . -Bbuild -G Ninja
  - cmake --build build
  - ./build/bin/unittests
